lime_profiler_profiler_index:
    pattern: /_memory_profiler/{run}/
    defaults: { _controller: LimeProfilerBundle:Profiler:index }

lime_profiler_profiler_function:
    pattern: /_memory_profiler/{run}/function/{function}/
    defaults: { _controller: LimeProfilerBundle:Profiler:function }

lime_profiler_profiler_callgraph:
    pattern: /_memory_profiler/{run}/callgraph/
    defaults: { _controller: LimeProfilerBundle:Profiler:callgraph }