imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:
    #    enabled:     true
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        auto_start:     true
    translator: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

services:
    twig.extension.debug:
       class: Twig_Extensions_Extension_Debug
       tags:
           - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    port:       %mailer_port%
    encryption: %mailer_encryption%
    username:   %mailer_user%
    password:   %mailer_password%
    spool:      { type: memory }

# JMS Security Extra Configutation
jms_security_extra:
    secure_all_services: false

# FOS User Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Lime\UserBundle\Entity\User
    profile:
        form:
            type: lime_user_profile
    #group:
    #    form:
    #        handler: lime_user.form.handler.group
    #    group_class: Lime\UserBundle\Entity\Group
    #    group_manager: lime_user.group_manager
    registration:
        form:
            type: lime_user_registration
            handler: lime_user.form.handler.registration
        confirmation:
            enabled: true

# Stoff Doctrine Extensions Configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

# Vich Uploader Configuration
vich_uploader:
    db_driver: orm
    web_dir_name: web
    twig: true
    mappings:
        profile_image:
            upload_dir: %kernel.root_dir%/../web/img/profile-images
            delete_on_remove: true
            inject_on_load: true
        artwork_image:
            upload_dir: %kernel.root_dir%/../web/img/artwork-images
            delete_on_remove: true
            inject_on_load: true
            namer: apealz.art.imgnamer.service
        artist_image:
            upload_dir: %kernel.root_dir%/../web/img/artist-images
            delete_on_remove: true
            inject_on_load: true
            namer: apealz.art.imgnamer.service
        product_image:
            upload_dir: %kernel.root_dir%/../web/img/product-images
            delete_on_remove: true
            inject_on_load: true
        product_image_mask:
            upload_dir: %kernel.root_dir%/../web/img/product-image-masks
            delete_on_remove: true
            inject_on_load: true

fos_rest:
    view:
        view_response_listener: force

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
