lime_admin_default_index:
    pattern: /
    defaults: { _controller: "LimeAdminBundle:Default:index" }

lime_config_index:
    resource: "@LimeAdminBundle/Resources/config/routing/config.yml"
    prefix:   /config
    
lime_admin_message:
    resource: "@LimeAdminBundle/Resources/config/routing/message.yml"
    prefix:   /messages