lime_user_admin_index:
    pattern: /
    defaults: { _controller: LimeUserBundle:Admin:index }

lime_user_admin_promote:
    pattern: /promote
    defaults: { _controller: LimeUserBundle:Admin:promote }

lime_user_admin_demote:
    pattern: /demote
    defaults: { _controller: LimeUserBundle:Admin:demote }